q = input('Digite alguma coisa:  ')
print(type(q))
print(q.isalnum())
print(q.isalpha())
print(q.isascii())
print(q.isdigit())
print(q.islower())
print(q.isdecimal())
print(q.isidentifier())
print(q.isnumeric())
print(q.isprintable())
print(q.isspace())
print(q.istitle())
print(q.isupper())
